### ISSUE TITLE
Getting guilds of user

### ISSUE THREAD

**Issue by lavgup** [alii/nextjs-discord-oauth#1]
Hey, thanks for creating this!

Would you be able to add guild functionality, or just explain how I would go about doing this? I've browsed some projects, and apparently I would need to save the session in a database?

I'm trying to keep the authentication of my dashboard very minimal (which this template does!), so I'd prefer not needing to save them into a database.

Thanks!

**Comment by alii** [comment]
Sure, so with the `access_token` provided, you can make a request to `/users/@me/guilds` with the access token as the `Authorization` header. For example

```ts
const request = await fetch("https://discord.com/api/v8/users/@me/guilds", {
	headers: {
		Authorization: `Bearer ${access_token}`,
	},
});

const guilds = await request.json();
```

And that will work :)

Sorry for the slow reply
